"""initial schema from unified Base

Revision ID: 1dd24dee40e8
Revises: 
Create Date: 2026-08-24 00:16:35.890673

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1dd24dee40e8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_thresholds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_tiers',
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_table('building_twins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('criticality_tier', sa.String(), nullable=False),
    sa.Column('solar_generation_kwh', sa.Float(), nullable=True),
    sa.Column('wind_generation_kwh', sa.Float(), nullable=True),
    sa.Column('consumption_kwh', sa.Float(), nullable=True),
    sa.Column('grid_import_kwh', sa.Float(), nullable=True),
    sa.Column('grid_export_kwh', sa.Float(), nullable=True),
    sa.Column('net_meter_units', sa.Float(), nullable=True),
    sa.Column('battery_soc_pct', sa.Float(), nullable=True),
    sa.Column('battery_health_pct', sa.Float(), nullable=True),
    sa.Column('tariff_inr_per_unit', sa.Float(), nullable=True),
    sa.Column('predicted_solar_tomorrow_kwh', sa.Float(), nullable=True),
    sa.Column('predicted_wind_tomorrow_kwh', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('building_twins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_twins_id'), ['id'], unique=False)

    op.create_table('decision_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('confidence_pct', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('alternative_considered', sa.Text(), nullable=True),
    sa.Column('expected_savings_inr', sa.Float(), nullable=True),
    sa.Column('expected_carbon_reduction_kg', sa.Float(), nullable=True),
    sa.Column('building_id', sa.String(), nullable=True),
    sa.Column('battery_soc_after_pct', sa.Float(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_logs_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_logs_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('vnm_sharing_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('sharing_ratio', sa.Float(), nullable=False),
    sa.Column('rerc_rule_reference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battery_twins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('soc_pct', sa.Float(), nullable=True),
    sa.Column('health_pct', sa.Float(), nullable=True),
    sa.Column('capacity_kwh', sa.Float(), nullable=True),
    sa.Column('charge_rate_max_kw', sa.Float(), nullable=True),
    sa.Column('discharge_rate_max_kw', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('voltage_v', sa.Float(), nullable=True),
    sa.Column('current_a', sa.Float(), nullable=True),
    sa.Column('power_kw', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building_twins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('battery_twins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battery_twins_id'), ['id'], unique=False)

    op.create_table('wind_turbine_twins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('wind_speed_mps', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('power_output_kw', sa.Float(), nullable=True),
    sa.Column('cut_in_speed_mps', sa.Float(), nullable=True),
    sa.Column('rated_speed_mps', sa.Float(), nullable=True),
    sa.Column('cut_out_speed_mps', sa.Float(), nullable=True),
    sa.Column('rated_power_kw', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building_twins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wind_turbine_twins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wind_turbine_twins_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wind_turbine_twins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wind_turbine_twins_id'))

    op.drop_table('wind_turbine_twins')
    with op.batch_alter_table('battery_twins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_battery_twins_id'))

    op.drop_table('battery_twins')
    op.drop_table('vnm_sharing_rules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('decision_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_decision_logs_decision_id'))
        batch_op.drop_index(batch_op.f('ix_decision_logs_building_id'))

    op.drop_table('decision_logs')
    with op.batch_alter_table('building_twins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_twins_id'))

    op.drop_table('building_twins')
    op.drop_table('building_tiers')
    op.drop_table('alert_thresholds')
    # ### end Alembic commands ###
